"use client";

import {
  AlertTriangle,
  BarChart3,
  Bell,
  Bot,
  Building2,
  Clock,
  Eye,
  FileQuestion,
  FileSpreadsheet,
  Filter,
  Handshake,
  LayoutDashboard,
  LineChart,
  ListChecks,
  MapPin,
  MessageSquare,
  Network,
  Package,
  Palette,
  RefreshCw,
  Share2,
  Sparkles,
  Target,
  TrendingDown,
  TrendingUp,
  UserMinus,
  Users,
  Workflow,
  Zap,
} from "lucide-react";

const SOLUTION_ICONS = {
  alertTriangle: AlertTriangle,
  barChart3: BarChart3,
  bell: Bell,
  bot: Bot,
  building2: Building2,
  clock: Clock,
  eye: Eye,
  fileQuestion: FileQuestion,
  fileSpreadsheet: FileSpreadsheet,
  filter: Filter,
  handshake: Handshake,
  layoutDashboard: LayoutDashboard,
  lineChart: LineChart,
  listChecks: ListChecks,
  mapPin: MapPin,
  messageSquare: MessageSquare,
  network: Network,
  package: Package,
  palette: Palette,
  refreshCw: RefreshCw,
  share2: Share2,
  sparkles: Sparkles,
  target: Target,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  userMinus: UserMinus,
  users: Users,
  workflow: Workflow,
  zap: Zap,
};

export function getSolutionIcon(iconKey) {
  return SOLUTION_ICONS[iconKey] ?? LayoutDashboard;
}
